server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
    timeout: 10000

mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: test-producer-group

dubbo:
  application:
    name: test-api
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
  scan:
    base-packages: com.hjp.provider.service

  provider:
    OaService:
      version: 1.0.0

  consumer:
    timeout: 120000

logging:
  file:
    path: D:/logs/hjp
